# Generated by Django 4.0.6 on 2022-07-28 00:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_item_watcher_item_watcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='listings'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Clothes', 'Clothes'), ('Electronics', 'Electronics'), ('Home', 'Home'), ('Toys', 'Toys')], max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='watcher',
            field=models.ManyToManyField(blank=True, related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
